set -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

set -s escape-time 0
set-option -g status-interval 1
set -g base-index 1
setw -g pane-base-index 1

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set -g repeat-time 500

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


set -g status-style 'bg=#282828,fg=#ebdbb2'

set -g status-left '#[bg=#d65d0e,fg=#282828,bold] #S #[bg=#282828,fg=#d65d0e]'
set -g status-left-length 30

set -g status-right '#[fg=#d79921]%Y-%m-%d #[fg=#ebdbb2]%H:%M '

set -g window-status-current-style 'bg=#d79921,fg=#282828,bold'
set -g window-status-current-format ' #I:#W '

set -g window-status-style 'bg=#282828,fg=#a89984'
set -g window-status-format ' #I:#W '

set -g pane-border-style 'fg=#504945'
set -g pane-active-border-style 'fg=#d65d0e'

set -g message-style 'bg=#d65d0e,fg=#282828,bold'

set -g window-style 'bg=#282828'
set -g window-active-style 'bg=#32302f'
