set -g mode-keys vi

bind -T copy-mode-vi y send -X copy-pipe-and-canel "pbcopy"

set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm:colors=256"

set -s escape-time 0
set-option -g status-interval 1
set -g base-index 1
setw -g pane-base-index 1
set -g window-style 'bg-colour239'
set -g window-active-style 'bg-colour234'

set -g prefix C-a

